apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detector
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
      - name: detector
        image: phishing-detector
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: detector-service
spec:
  selector:
    app: detector
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort

# Apply to Minikube:
# kubectl apply -f k8s/detector-deployment.yaml

# Access it:
# minikube service detector-service