apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: phishing-simulator
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: simulator-service
spec:
  selector:
    app: simulator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort

# Apply to Minikube:
# kubectl apply -f k8s/simulator-deployment.yaml

# Access it:
# minikube service simulator-service
